""" "add_location_connections_and_update_game_entity"

Revision ID: 034f266e495b
Revises: aebd9bc93087
Create Date: 2025-07-08 22:37:08.573255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "034f266e495b"
down_revision: Union[str, Sequence[str], None] = "aebd9bc93087"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location_connection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_two_way", sa.Boolean(), nullable=True),
        sa.Column("source_location_id", sa.Integer(), nullable=False),
        sa.Column("destination_location_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_location_id"],
            ["location.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("game_entity", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("current_location_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_game_entity_location", "location", ["current_location_id"], ["id"]
        )

    with op.batch_alter_table("map_point", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("default_location_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_map_point_location", "location", ["default_location_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("map_point", schema=None) as batch_op:
        batch_op.drop_constraint("fk_map_point_location", type_="foreignkey")
        batch_op.drop_column("default_location_id")

    with op.batch_alter_table("game_entity", schema=None) as batch_op:
        batch_op.drop_constraint("fk_game_entity_location", type_="foreignkey")
        batch_op.drop_column("current_location_id")

    op.drop_table("location_connection")
    # ### end Alembic commands ###
