""""Add_summary_to_MapPoint_and_is_entry_point_to_Location"

Revision ID: 329babde56d8
Revises: f7f9dfe29556
Create Date: 2025-07-19 22:30:49.209829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '329babde56d8'
down_revision: Union[str, Sequence[str], None] = 'f7f9dfe29556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_entry_point', sa.Boolean(), nullable=True))

    with op.batch_alter_table('map_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary', sa.Text(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('default_location_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('map_point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_location_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'location', ['default_location_id'], ['id'])
        batch_op.drop_column('summary')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('is_entry_point')

    # ### end Alembic commands ###
