"""Add_max_attributes

Revision ID: 7a21b3d74a12
Revises: e1c340195dac
Create Date: 2025-07-08 17:03:37.805253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a21b3d74a12'
down_revision: Union[str, Sequence[str], None] = 'e1c340195dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_entity', sa.Column('max_strength', sa.Integer(), nullable=True))
    op.add_column('game_entity', sa.Column('max_dexterity', sa.Integer(), nullable=True))
    op.add_column('game_entity', sa.Column('max_willpower', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_entity', 'max_willpower')
    op.drop_column('game_entity', 'max_dexterity')
    op.drop_column('game_entity', 'max_strength')
    # ### end Alembic commands ###
