"""Initial_migration

Revision ID: e1c340195dac
Revises:
Create Date: 2025-07-08 16:21:55.520439

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1c340195dac"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "log_entry",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_dict", sa.JSON(), nullable=True),
        sa.Column("involved_entities", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "map_point",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("position_x", sa.Integer(), nullable=True),
        sa.Column("position_y", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "game_entity",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("hp", sa.Integer(), nullable=True),
        sa.Column("max_hp", sa.Integer(), nullable=True),
        sa.Column("strength", sa.Integer(), nullable=True),
        sa.Column("dexterity", sa.Integer(), nullable=True),
        sa.Column("willpower", sa.Integer(), nullable=True),
        sa.Column("fatigue", sa.Integer(), nullable=True),
        sa.Column("armor", sa.Integer(), nullable=True),
        sa.Column("disposition", sa.String(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("pronouns", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("background", sa.String(), nullable=True),
        sa.Column("bond", sa.String(), nullable=True),
        sa.Column("omen", sa.String(), nullable=True),
        sa.Column("is_retired", sa.Boolean(), nullable=True),
        sa.Column("attacks", sa.JSON(), nullable=True),
        sa.Column("current_map_point_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["current_map_point_id"],
            ["map_point.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "location",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("contents", sa.JSON(), nullable=True),
        sa.Column("map_point_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["map_point_id"],
            ["map_point.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "path",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("watches", sa.Integer(), nullable=True),
        sa.Column("feature", sa.String(), nullable=True),
        sa.Column("start_point_id", sa.Integer(), nullable=False),
        sa.Column("end_point_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["end_point_id"],
            ["map_point.id"],
        ),
        sa.ForeignKeyConstraint(
            ["start_point_id"],
            ["map_point.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=True),
        sa.Column("slots", sa.Integer(), nullable=True),
        sa.Column("tags", sa.JSON(), nullable=True),
        sa.Column("owner_entity_id", sa.Integer(), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["location.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_entity_id"],
            ["game_entity.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    op.drop_table("path")
    op.drop_table("location")
    op.drop_table("game_entity")
    op.drop_table("map_point")
    op.drop_table("log_entry")
    # ### end Alembic commands ###
