""" "add_scars_and_is_hostile_to_game_entity"

Revision ID: f7f9dfe29556
Revises: 034f266e495b
Create Date: 2025-07-17 17:09:17.597194

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7f9dfe29556"
down_revision: Union[str, Sequence[str], None] = "034f266e495b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("game_entity", sa.Column("is_hostile", sa.Boolean(), nullable=True))
    op.add_column("game_entity", sa.Column("scars", sa.Text(), nullable=True))
    op.create_foreign_key(
        None, "game_entity", "location", ["current_location_id"], ["id"]
    )
    op.add_column(
        "map_point", sa.Column("default_location_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        None, "map_point", "location", ["default_location_id"], ["id"], use_alter=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "map_point", type_="foreignkey")
    op.drop_column("map_point", "default_location_id")
    op.drop_constraint(None, "game_entity", type_="foreignkey")
    op.drop_column("game_entity", "scars")
    op.drop_column("game_entity", "is_hostile")
    # ### end Alembic commands ###
